displayName: gatekeeper
type: middleware
import: github.com/fatiharge/gatekeeper
summary: Gatekeeper is a Traefik middleware plugin that verifies the Authorization header by sending a GET request to an external URL, allowing the request to proceed if 200 OK is returned, otherwise blocking it.


# Configuration data for your plugin.
# This is mandatory,
# and Plugins Catalog will try to execute the plugin with the data you provide as part of its startup validity tests.
testData:
  Headers:
    Foo: Bar